name: ruff

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install deps
        run: uv sync

      - name: Run ruff
        run: make ruff
